"""add note3-5 and note_options table

Revision ID: 55b49e43fd3b
Revises: 
Create Date: 2026-04-02 09:38:08.785614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b49e43fd3b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_field', sa.String(length=10), nullable=False),
    sa.Column('option_value', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_field', 'option_value', name='unique_note_option')
    )
    with op.batch_alter_table('note_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_options_note_field'), ['note_field'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note3', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('note4', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('note5', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('note5')
        batch_op.drop_column('note4')
        batch_op.drop_column('note3')

    with op.batch_alter_table('note_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_options_note_field'))

    op.drop_table('note_options')
    # ### end Alembic commands ###
